# ResearchRAG Baseline Configuration
# This configuration uses GPT-4o-mini as the baseline model

llm:
  type: openai
  model: gpt-4o-mini
  temperature: 0.1
  max_tokens: 1000
  # api_key: ${OPENAI_API_KEY}  # Set via environment variable

embedding:
  type: openai
  model: text-embedding-ada-002
  # api_key: ${OPENAI_API_KEY}  # Set via environment variable

chunking:
  type: fixed-size
  chunk_size: 1000
  chunk_overlap: 200
  separator: "\n"

retrieval:
  type: vector-similarity
  top_k: 5
  similarity_threshold: 0.0

evaluation:
  enabled_metrics:
    - precision-recall
    - timing
    - ragas

dataset:
  evaluation_subset_size: 50
  save_qa_pairs: true

pipeline:
  include_context: true
  max_context_length: 4000
